CREATE TABLE CURRENCY (
    CODE VARCHAR(3) NOT NULL PRIMARY KEY,
    DESCRIPTION VARCHAR(30) NOT NULL
);

CREATE TABLE CUSTOMER (
    ID NUMBER NOT NULL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
);

CREATE TABLE ACCOUNT (
    ID NUMBER NOT NULL PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    TYPE VARCHAR(10) NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL ,
    FOREIGN KEY (CURRENCY) REFERENCES CURRENCY(CODE),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

CREATE TABLE TRANSACTION(
    ID NUMBER NOT NULL PRIMARY KEY,
    ACCOUNT_ID NUMBER NOT NULL,
    VALUE_DATE DATE NOT NULL,
    TYPE VARCHAR(10) NOT NULL,
    AMOUNT NUMERIC(15,2) NOT NULL,
    DESCRIPTION VARCHAR(50) NOT NULL,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID)
);

CREATE index idx_account
on ACCOUNT (CUSTOMER_ID);

CREATE index idx_account_transaction
on TRANSACTION (ACCOUNT_ID);
